cocoms_20190108/src/main/java/cocoms/copyright/entity/BoardVO.java
package cocoms.copyright.entity;

import java.util.*;

public class BoardVO extends DefaultVO {

	private static final long serialVersionUID = 1L;

	private String boardSeqNo = ""; 	// 
	private String boardId    = ""; 	// 
	private String regDate    = ""; 	// 
	private String regTime    = ""; 	// 
	private String regId      = ""; 	// 
	private String title      = ""; 	// 
	private String content    = ""; 	// 
	private String content2   = ""; 	// 
	private String ref        = ""; 	// 
	private String depth      = ""; 	// 
	private String position   = ""; 	// 
	private String hit        = ""; 	// 
	private String dref       = ""; 	// 
	private String delGubun   = ""; 	// 
	private String download_hit        = ""; 	// 
	private String regName    = ""; 	// 
	private String replyYn    = ""; 	//

	private List<BoardFileDataVO> boardFileDataList = new ArrayList<BoardFileDataVO>(); 	// 

	public BoardVO() {
	}
	public BoardVO(String boardSeqNo) {
		this.boardSeqNo = boardSeqNo;
	}
	
	/*
	 * Special Getters
	 */
	public String getRegDateStr() {
		
		if (regDate != null && regDate.length() == 8) {
			return regDate.substring(0,  4)+"-"+regDate.substring(4, 6)+"-"+regDate.substring(6, 8);
		}
		
		return regDate;
	}
	
	/*
	 * Getters and Setters
	 */
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	public String getReplyYn() {
		return replyYn;
	}
	public void setReplyYn(String replyYn) {
		this.replyYn = replyYn;
	}
	public String getRegName() {
		return regName;
	}
	public void setRegName(String regName) {
		this.regName = regName;
	}
	public List<BoardFileDataVO> getBoardFileDataList() {
		return boardFileDataList;
	}
	public void setBoardFileDataList(List<BoardFileDataVO> boardFileDataList) {
		this.boardFileDataList = boardFileDataList;
	}
	public String getBoardSeqNo() {
		return boardSeqNo;
	}
	public void setBoardSeqNo(String boardSeqNo) {
		this.boardSeqNo = boardSeqNo;
	}
	public String getRegDate() {
		return regDate;
	}
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
	public String getRegTime() {
		return regTime;
	}
	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}
	public String getRegId() {
		return regId;
	}
	public void setRegId(String regId) {
		this.regId = regId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getContent2() {
		return content2;
	}
	public void setContent2(String content2) {
		this.content2 = content2;
	}
	public String getRef() {
		return ref;
	}
	public void setRef(String ref) {
		this.ref = ref;
	}
	public String getDepth() {
		return depth;
	}
	public void setDepth(String depth) {
		this.depth = depth;
	}
	public String getPosition() {
		return position;
	}
	public void setPosition(String position) {
		this.position = position;
	}
	public String getHit() {
		return hit;
	}
	public void setHit(String hit) {
		this.hit = hit;
	}
	public String getDref() {
		return dref;
	}
	public void setDref(String dref) {
		this.dref = dref;
	}
	public String getDelGubun() {
		return delGubun;
	}
	public void setDelGubun(String delGubun) {
		this.delGubun = delGubun;
	}
	public String getDownload_hit() {
		return download_hit;
	}
	public void setDownload_hit(String download_hit) {
		this.download_hit = download_hit;
	}

}

cocoms_20190108/src/main/java/cocoms/copyright/entity/LoginVO.java
package cocoms.copyright.entity;

import org.apache.commons.lang3.StringUtils;

import cocoms.copyright.common.CommonUtils;

public class LoginVO extends DefaultVO {

	private static final long serialVersionUID = 1L;

	private String loginId     = "";	//
	private String memberSeqNo = "";	//
	private String pwd         = "";	//
	private String regDate     = "";	//
	private String delGubun    = "";	//
	private String regNo       = "";	//
	private String coGubun     = "";	//
	private String lastLoginDate	= "";	//
	private String lastLoginTime	= "";	//

	private String certType      = "";	// 1: 개인, 2: 법인
	
	private String statCd          = "";	//
	private String ceoName         = "";	//
	private String ceoMobile       = "";	//
	private String ceoEmail        = "";	//
	private String conditionCd     = "";	//
	private String conDetailCd     = "";	//
	private String coName          = "";	//
	private String coNo            = "";	// 사업자번호
	private String bubNo           = "";	//
	private String sms             = "";	//
	private String smsAgree        = "";
	private String appno2 		   = "";
	public LoginVO() {
	}
	public LoginVO(String loginId) {
		this.loginId = loginId;
	}
	
	public String getAppno2() {
		return appno2;
	}
	public void setAppno2(String appno2) {
		this.appno2 = appno2;
	}
	/*
	 * Special Getters
	 */
	public String getRegDateStr() {
		
		if (regDate != null && regDate.length() == 8) {
			return regDate.substring(0,  4)+"-"+regDate.substring(4, 6)+"-"+regDate.substring(6, 8);
		}
		
		return regDate;
	}
	public String getLastLoginDateStr() {
		
		if (lastLoginDate != null && lastLoginDate.length() == 8) {
			return lastLoginDate.substring(0,  4)+"-"+lastLoginDate.substring(4, 6)+"-"+lastLoginDate.substring(6, 8);
		}
		
		return lastLoginDate;
	}
	public String getLastLoginTimeStr() {
		
		if (lastLoginTime != null && lastLoginTime.length() == 6) {
			return lastLoginTime.substring(0, 2)+":"+lastLoginTime.substring(2, 4)+":"+lastLoginTime.substring(4, 6);
		}
		
		return lastLoginTime;
	}
	public String getBubNoStr() {
		
		if (StringUtils.isNotEmpty(bubNo)) {
			return CommonUtils.toFormat(bubNo, "######-#######");
		}
		
		return bubNo;
	}
	public String getCoNoStr() {
		
		if (StringUtils.isNotEmpty(coNo)) {
			return CommonUtils.toFormat(coNo, "###-##-#####");
		}
		
		return coNo;
	}
	
	/*
	 * Getters and Setters
	 */
	public String getMemberSeqNo() {
		return memberSeqNo;
	}
	public void setMemberSeqNo(String memberSeqNo) {
		this.memberSeqNo = memberSeqNo;
	}
	public String getStatCd() {
		return statCd;
	}
	public void setStatCd(String statCd) {
		this.statCd = statCd;
	}
	public String getSmsAgree() {
		return smsAgree;
	}
	public void setSmsAgree(String smsAgree) {
		this.smsAgree = smsAgree;
	}
	public String getSms() {
		return sms;
	}
	public void setSms(String sms) {
		this.sms = sms;
	}
	public String getCoName() {
		return coName;
	}
	public void setCoName(String coName) {
		this.coName = coName;
	}
	public String getConditionCd() {
		return conditionCd;
	}
	public void setConditionCd(String conditionCd) {
		this.conditionCd = conditionCd;
	}
	public String getConDetailCd() {
		return conDetailCd;
	}
	public void setConDetailCd(String conDetailCd) {
		this.conDetailCd = conDetailCd;
	}
	public String getCoNo() {
		return coNo;
	}
	public void setCoNo(String coNo) {
		this.coNo = coNo;
	}
	public String getBubNo() {
		return bubNo;
	}
	public void setBubNo(String bubNo) {
		this.bubNo = bubNo;
	}
	public String getCeoMobile() {
		return ceoMobile;
	}
	public void setCeoMobile(String ceoMobile) {
		this.ceoMobile = ceoMobile;
	}
	public String getLastLoginDate() {
		return lastLoginDate;
	}
	public void setLastLoginDate(String lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}
	public String getLastLoginTime() {
		return lastLoginTime;
	}
	public void setLastLoginTime(String lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
	public String getCeoName() {
		return ceoName;
	}
	public void setCeoName(String ceoName) {
		this.ceoName = ceoName;
	}
	public String getCeoEmail() {
		return ceoEmail;
	}
	public void setCeoEmail(String ceoEmail) {
		this.ceoEmail = ceoEmail;
	}
	public String getCertType() {
		return certType;
	}
	public void setCertType(String certType) {
		this.certType = certType;
	}
	public String getDelGubun() {
		return delGubun;
	}
	public void setDelGubun(String delGubun) {
		this.delGubun = delGubun;
	}
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	public String getRegDate() {
		return regDate;
	}
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
	public String getRegNo() {
		return regNo;
	}
	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}
	public String getCoGubun() {
		return coGubun;
	}
	public void setCoGubun(String coGubun) {
		this.coGubun = coGubun;
	}
}

cocoms_20190108/src/main/java/cocoms/copyright/entity/ReportVO.java
package cocoms.copyright.entity;

import org.apache.commons.lang3.StringUtils;

public class ReportVO extends DefaultVO {

	private static final long serialVersionUID = 1L;

	private String memberSeqNo     = "";	//
	private String appNo           = "";	//
	private String coName          = "";	//
	private String year1           = "";	//
	private String year2           = "";	//
	private String year3           = "";	//
	private String year4           = "";	//
	private String year5           = "";	//
	private String appNo1          = "";	//
	private String appNo2          = "";	//
	private String regDate         = "";	//
	private String regTime         = "";	//
	
	/*
	 * Special Getters
	 */
	public String getAppNoStr() {
		
		String str = "";
		if (StringUtils.isNotEmpty(appNo2)) {
			str += "제 ";
			if (StringUtils.isNotEmpty(appNo)) {
				str += appNo + "-";
			}
			str += appNo2 + "호";
		}
		
		return str;
	}
	
	/*
	 * Getters and Setters
	 */
	public String getMemberSeqNo() {
		return memberSeqNo;
	}
	public void setMemberSeqNo(String memberSeqNo) {
		this.memberSeqNo = memberSeqNo;
	}
	public String getAppNo() {
		return appNo;
	}
	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}
	public String getCoName() {
		return coName;
	}
	public void setCoName(String coName) {
		this.coName = coName;
	}
	public String getYear1() {
		return year1;
	}
	public void setYear1(String year1) {
		this.year1 = year1;
	}
	public String getYear2() {
		return year2;
	}
	public void setYear2(String year2) {
		this.year2 = year2;
	}
	public String getYear3() {
		return year3;
	}
	public void setYear3(String year3) {
		this.year3 = year3;
	}
	public String getYear4() {
		return year4;
	}
	public void setYear4(String year4) {
		this.year4 = year4;
	}
	public String getYear5() {
		return year5;
	}
	public void setYear5(String year5) {
		this.year5 = year5;
	}
	public String getAppNo1() {
		return appNo1;
	}
	public void setAppNo1(String appNo1) {
		this.appNo1 = appNo1;
	}
	public String getAppNo2() {
		return appNo2;
	}
	public void setAppNo2(String appNo2) {
		this.appNo2 = appNo2;
	}
	public String getRegDate() {
		return regDate;
	}
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
	public String getRegTime() {
		return regTime;
	}
	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}
		
}

cocoms_20190108/src/main/java/cocoms/copyright/entity/RpMgmVO.java
package cocoms.copyright.entity;

public class RpMgmVO extends DefaultVO {

	private static final long serialVersionUID = 1L;

	private String rpMgmSeqNo    = "";	//
	private String memberSeqNo   = "";	//
	private String regDate       = "";	//
	private String regTime       = "";	//
	private String statCd        = "";	//
	private String rpMemo        = "";	//
	private String file1Path     = "";	//
	private String file2Path     = "";	//
	private String file3Path     = "";	//
	private String file4Path     = "";	//
	private String file5Path     = "";	//
	private String interFilename = "";	//
	private String interFilepath = "";	//
	private String certInfoSeqNo = "";	//
	private String retYn         = "";	//
	
	public RpMgmVO() {
	}
	public RpMgmVO(String rpMgmSeqNo) {
		this.rpMgmSeqNo = rpMgmSeqNo;
	}
	
	/*
	 * Special Getters
	 */
	public String getRegDateStr() {
		
		if (regDate != null && regDate.length() == 8) {
			return regDate.substring(0, 4)+"-"+regDate.substring(4, 6)+"-"+regDate.substring(6, 8);
		}
		
		return regDate;
	}
	public String getRegTimeStr() {
		
		if (regTime != null && regTime.length() == 6) {
			return regTime.substring(0, 2)+":"+regTime.substring(2, 4)+":"+regTime.substring(4, 6);
		}
		
		return regTime;
	}
	
	/*
	 * Getters and Setters
	 */
	public String getMemberSeqNo() {
		return memberSeqNo;
	}
	public void setMemberSeqNo(String memberSeqNo) {
		this.memberSeqNo = memberSeqNo;
	}
	public String getStatCd() {
		return statCd;
	}
	public void setStatCd(String statCd) {
		this.statCd = statCd;
	}
	public String getFile1Path() {
		return file1Path;
	}
	public void setFile1Path(String file1Path) {
		this.file1Path = file1Path;
	}
	public String getFile2Path() {
		return file2Path;
	}
	public void setFile2Path(String file2Path) {
		this.file2Path = file2Path;
	}
	public String getFile3Path() {
		return file3Path;
	}
	public void setFile3Path(String file3Path) {
		this.file3Path = file3Path;
	}
	public String getFile4Path() {
		return file4Path;
	}
	public void setFile4Path(String file4Path) {
		this.file4Path = file4Path;
	}
	public String getRpMgmSeqNo() {
		return rpMgmSeqNo;
	}
	public void setRpMgmSeqNo(String rpMgmSeqNo) {
		this.rpMgmSeqNo = rpMgmSeqNo;
	}
	public String getRegDate() {
		return regDate;
	}
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}
	public String getRegTime() {
		return regTime;
	}
	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}
	public String getRpMemo() {
		return rpMemo;
	}
	public void setRpMemo(String rpMemo) {
		this.rpMemo = rpMemo;
	}
	public String getInterFilename() {
		return interFilename;
	}
	public void setInterFilename(String interFilename) {
		this.interFilename = interFilename;
	}
	public String getInterFilepath() {
		return interFilepath;
	}
	public void setInterFilepath(String interFilepath) {
		this.interFilepath = interFilepath;
	}
	public String getCertInfoSeqNo() {
		return certInfoSeqNo;
	}
	public void setCertInfoSeqNo(String certInfoSeqNo) {
		this.certInfoSeqNo = certInfoSeqNo;
	}
	public String getRetYn() {
		return retYn;
	}
	public void setRetYn(String retYn) {
		this.retYn = retYn;
	}
	public String getFile5Path() {
		return file5Path;
	}
	public void setFile5Path(String file5Path) {
		this.file5Path = file5Path;
	}
	
}

cocoms_20190108/src/main/java/cocoms/copyright/web/form/ReportForm.java
package cocoms.copyright.web.form;

import java.util.*;

import cocoms.copyright.entity.*;

public class ReportForm extends ReportInfoVO {

	private static final long serialVersionUID = 1L;

	private List<String> writingKind = new ArrayList<String>();
	private List<String> permKind = new ArrayList<String>();

	private List<String> inWorkNum = new ArrayList<String>();
	private List<String> outWorkNum = new ArrayList<String>();
	private List<String> workSum = new ArrayList<String>();

	private List<String> inRental = new ArrayList<String>();
	private List<String> outRental = new ArrayList<String>();
	private List<String> rentalSum = new ArrayList<String>();
	private List<String> inChrg = new ArrayList<String>();
	private List<String> outChrg = new ArrayList<String>();
	private List<String> chrgSum = new ArrayList<String>();
	private List<String> inChrgRate = new ArrayList<String>();
	private List<String> outChrgRate = new ArrayList<String>();
	private List<String> avgChrgRate = new ArrayList<String>();

	/*
	 * Getters and Setters
	 */
	public List<String> getOutWorkNum() {
		return outWorkNum;
	}
	public void setOutWorkNum(List<String> outWorkNum) {
		this.outWorkNum = outWorkNum;
	}
	public List<String> getWritingKind() {
		return writingKind;
	}
	public void setWritingKind(List<String> writingKind) {
		this.writingKind = writingKind;
	}
	public List<String> getPermKind() {
		return permKind;
	}
	public void setPermKind(List<String> permKind) {
		this.permKind = permKind;
	}
	public List<String> getInWorkNum() {
		return inWorkNum;
	}
	public void setInWorkNum(List<String> inWorkNum) {
		this.inWorkNum = inWorkNum;
	}
	public List<String> getWorkSum() {
		return workSum;
	}
	public void setWorkSum(List<String> workSum) {
		this.workSum = workSum;
	}
	public List<String> getInRental() {
		return inRental;
	}
	public void setInRental(List<String> inRental) {
		this.inRental = inRental;
	}
	public List<String> getOutRental() {
		return outRental;
	}
	public void setOutRental(List<String> outRental) {
		this.outRental = outRental;
	}
	public List<String> getRentalSum() {
		return rentalSum;
	}
	public void setRentalSum(List<String> rentalSum) {
		this.rentalSum = rentalSum;
	}
	public List<String> getInChrg() {
		return inChrg;
	}
	public void setInChrg(List<String> inChrg) {
		this.inChrg = inChrg;
	}
	public List<String> getOutChrg() {
		return outChrg;
	}
	public void setOutChrg(List<String> outChrg) {
		this.outChrg = outChrg;
	}
	public List<String> getChrgSum() {
		return chrgSum;
	}
	public void setChrgSum(List<String> chrgSum) {
		this.chrgSum = chrgSum;
	}
	public List<String> getInChrgRate() {
		return inChrgRate;
	}
	public void setInChrgRate(List<String> inChrgRate) {
		this.inChrgRate = inChrgRate;
	}
	public List<String> getOutChrgRate() {
		return outChrgRate;
	}
	public void setOutChrgRate(List<String> outChrgRate) {
		this.outChrgRate = outChrgRate;
	}
	public List<String> getAvgChrgRate() {
		return avgChrgRate;
	}
	public void setAvgChrgRate(List<String> avgChrgRate) {
		this.avgChrgRate = avgChrgRate;
	}

}

cocoms_20190108/src/main/webapp/WEB-INF/jsp/cocoms/usr/mypage/mypage_view.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c"      uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form"   uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="ui"     uri="http://egovframework.gov/ctl/ui" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<jsp:include page="/WEB-INF/jsp/cocoms/comm/header.jsp" flush="true">
	<jsp:param name="title" value="" />
	<jsp:param name="type" value="mypage" />
	<jsp:param name="nav1" value="마이페이지" />
	<jsp:param name="nav2" value="회원정보 수정" />
</jsp:include>
	
	<script>
	window.onload = function () {
     var chg = ${chg};
     if(chg=='1'){
    	 alert("비밀번호 변경이 완료되었습니다.")
     }else{
    	 }
     }
	</script>
	<div class="container">
		<div class="menu_aside">
			<h2 class="tit_bar my mt">마이페이지</h2>
			<ul>
				<li class="active"><a href="<c:url value="/mypage" />">회원정보 수정</a></li>
				<li><a href="<c:url value="/report" />">신고/허가 내역</a></li>
				<%-- <li><a href="<c:url value="/qna" />">1:1문의 내역</a></li> --%>
				<li><a href="<c:url value="/charge" />">결제내역</a></li>
				<li><a href="<c:url value="/history" />">신고서 발급내역</a></li>
		
			</ul>
		</div>
		<!-- //menu_aside -->
		<div class="cont_notice mypage">
			<h2 class="tit_bar mt">회원정보 수정</h2>
			<div style="position: relative; font-size: 18px; color: #4b4a4a; font-weight: 600; overflow: hidden; padding: 26px 0 12px;">
				회원정보
				<div style="position: absolute; right: 0; bottom: 7px;">
					<a href="<c:url value="/appl/sub/new" />" class="btn btn_style1">대리중개업신청</a>
					<a href="<c:url value="/appl/trust/new" />" class="btn btn_style1">신탁관리업신청</a>
				</div>
			</div>
			<div class="table_area list_top">
				<table>
					<caption>회원정보</caption>
					<colgroup>
						<col style="width:200px" />
						<col style="width:auto" />
					</colgroup>
					<tbody>
						<tr>
							<th>가입일자</th>
							<td>
								<c:out value="${login.regDateStr}" />
							</td>
						</tr>
						<tr>
							<th>회원구분</th>
							<td>
								<c:if test="${member.coGubunCd eq '1'}">
									개인회원
								</c:if>
								<c:if test="${member.coGubunCd eq '2'}">
									사업자회원
								</c:if>
							</td>
						</tr>
						<tr>
							<th>이름 <c:if test="${member.coGubunCd eq '2'}">(담당자)</c:if></th>
							<td>
								<c:out value="${member.ceoName}" />
							</td>
						</tr>
						<tr>
							<th>아이디</th>
							<td>
								<c:out value="${login.loginId}" />
							</td>
						</tr>
						<tr>
							<th>휴대전화번호</th>
							<td>
								<c:out value="${member.ceoMobile}" />
							</td>
						</tr>
						<tr>
							<th>이메일 주소</th>
							<td>
								<c:out value="${member.ceoEmail}" />
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<!-- //table_area -->
			<div style="position: relative; font-size: 18px; color: #4b4a4a; font-weight: 600; overflow: hidden; padding: 26px 0 12px;">
				사업자정보
			</div>
			<div class="table_area list_top">
				<table>
					<caption>사업자정보</caption>
					<colgroup>
						<col style="width:200px" />
						<col style="width:auto" />
					</colgroup>
					<tbody>
						<tr>
							<th>회사명</th>
							<td>
								<c:out value="${member.coName}" />
							</td>
						</tr>
						<tr>
							<th>사업자등록번호</th>
							<td>
								<c:out value="${member.coNoStr}" />
							</td>
						</tr>
						<tr>
							<th>대표자명</th>
							<td>
								<c:out value="${member.ceoName}" />
							</td>
						</tr>
						<tr>
							<th>법인등록번호</th>
							<td>
								<c:out value="${member.bubNoStr}" />
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<!-- //table_area -->
			<div class="button_area">
				<a href="<c:url value="/mypage/edit" />" class="btn btn_style2">수정</a>
			</div>
		</div>
		<!-- //cont_notice -->		
	</div>
	<!-- //container -->

<jsp:include page="/WEB-INF/jsp/cocoms/comm/footer.jsp" flush="true">
	<jsp:param name="js" value="mypage" />
</jsp:include>
 

cocoms_20190108/src/main/webapp/WEB-INF/jsp/cocoms/usr/mypage/qna_view.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c"      uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form"   uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="ui"     uri="http://egovframework.gov/ctl/ui" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<jsp:include page="/WEB-INF/jsp/cocoms/comm/header.jsp" flush="true">
	<jsp:param name="title" value="" />
	<jsp:param name="type" value="mypage" />
	<jsp:param name="nav1" value="마이페이지" />
	<jsp:param name="nav2" value="1:1문의내역" />
</jsp:include>
	
	<div class="container">
		<div class="menu_aside">
			<h2 class="tit_bar my mt">마이페이지</h2>
			<ul>
				<li><a href="<c:url value="/mypage" />">회원정보 수정</a></li>
				<li><a href="<c:url value="/report" />">신고/허가 내역</a></li>
				<li class="active"><a href="<c:url value="/qna" />">1:1문의 내역</a></li>
				<li><a href="<c:url value="/charge" />">결제내역</a></li>
				<li><a href="<c:url value="/history" />">신고서 발급내역</a></li>
			</ul>
		</div>
		<!-- //menu_aside -->
		<div class="cont_notice mypage mypage_2">
			<h2 class="tit_bar mt">1:1문의내역</h2>
			<div class="table_area view">
				<table>
					<caption>공지사항</caption>
					<thead>
						<tr> 	 	 	
							<th class="subject">
								<c:out value="${data.title}" />
								<div class="date">
									<c:out value="${data.regDateStr}" />
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="cont">
								${data.content2}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<!-- //table_area -->
			
			<c:forEach var="item" items="${list}" varStatus="status">
				<div class="table_area view">
					<table>
						<caption>공지사항</caption>
						<thead>
							<tr> 	 	 	
								<th class="subject re">
									<strong class="txt_re">Re.</strong> 
									<c:out value="${item.title}" />
									<div class="date">
										<c:out value="${item.regDateStr}" />
									</div>
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="cont">
									${item.content2}
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<!-- //table_area -->
			</c:forEach>
			
			<div class="button_area">
				<a href="" id="remove2" class="btn btn_style2">삭제</a>
				<a href="<c:url value="/qna" />" class="btn btn_style1">목록</a>
			</div>
		</div>
		<!-- //cont_notice -->		
	</div>
	<!-- //container -->
	
<jsp:include page="/WEB-INF/jsp/cocoms/comm/footer.jsp" flush="true">
	<jsp:param name="js" value="mypage" />
</jsp:include>
 